apiVersion: v1
kind: Service
metadata:
  labels:
    service: {{ .Values.kafka.appName }}
  name: {{ .Values.kafka.appName }}
spec:
  clusterIP: None
  selector:
    service: {{ .Values.kafka.appName }}
  ports:
    - port: {{ .Values.kafka.service.port }}
      targetPort: {{ .Values.kafka.service.targetPort }}