version: '3.7'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092     #for running quarkus locally
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092        #for running quarkus from docker
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_container:/data/db
#  quarkus:
#    image: aryantripathi2003/spotify-api:latest
#    depends_on:
#      - kafka
#      - mongodb
#      - redis
#      - zookeeper
#    ports:
#      - "8080:8080"
  redis:
    image: redis/redis-stack:latest
    environment:
      REDIS_ARGS: --save 20 1 --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  elasticsearch:
#    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
    image: elasticsearch:8.0.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
volumes:
  mongodb_data_container:
  redis_data:
  esdata:

