apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
        - name: {{ .Values.appName }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          livenessProbe:
            tcpSocket:
              port: 6379
            initialDelaySeconds: 20
            periodSeconds: 5
          readinessProbe:
            exec:
              command: [ "redis-cli", "ping" ]
            initialDelaySeconds: 5
            periodSeconds: 5
          startupProbe:
            tcpSocket:
              port: 6379
            failureThreshold: 30
            periodSeconds: 10
          #          ports:
          #            - containerPort: 6379
          env:
            - name: REDIS_ARGS
              value: "--save 20 1 --appendonly yes"
          volumeMounts:
            - mountPath: "/data"
              name: {{ .Values.volume.name }}
      volumes:
        - name: {{ .Values.volume.name }}
          persistentVolumeClaim:
            claimName: {{ .Values.volume.pvc.name }}