apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.volume.pv.name }}
spec:
  capacity:
    storage: {{ .Values.volume.pv.storage }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/mongodb"
    type: DirectoryOrCreate
  storageClassName: standard