apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.volume.persistentVolumeClaim.name }}
spec:
  volumeName: {{ .Values.volume.persistentVolume.name }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.volume.persistentVolumeClaim.storage }}